ms/distribution/views.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for

from ms.db import query
from ms.db.models import (
    Distribution,
    Product,
    Share,
    ShareModel,
    Station,
    StationHistory,
    Unit,
    db,
)

distribution = Blueprint("distribution", __name__)


@distribution.before_request
def check_distribution_in_progress():
    # check if dist is in progress, else redirect to start it
    if not Distribution.current().in_progress:
        if not request.endpoint == "distribution.trigger":
            return redirect(url_for("distribution.trigger"))


@distribution.route("/overview")
def overview():

    dist = Distribution.current()
    data = query.distribution_overview(dist)

    return render_template(
        "distribution/overview.html", data=data, dist=dist, dist_info=dist.information
    )


@distribution.route("/start", methods=["GET", "POST"])
def trigger():

    if request.method == "POST":

        dist = Distribution.current()
        distribute = request.form["distribution"]

        if distribute == "start" and not dist.in_progress:

            dist = Distribution(**dict(in_progress=True))
            db.session.add(dist)
            db.session.commit()
            Station.archive_all(dist.id)

            flash("Verteilung gestartet! Es kann losgehen!", category="primary")
            return redirect(url_for("products.products_view"), 302)

        elif distribute == "stop" and dist.in_progress:

            dist = Distribution.current()
            stations = StationHistory.query.filter_by(distribution_id=dist.id).all()
            dist.in_progress = False
            db.session.add(dist)
            [db.session.delete(share) for share in dist.shares]
            [db.session.delete(station) for station in stations]
            db.session.commit()

            return redirect(url_for("stations.stations_view"), 302)

        return abort(404)

    return render_template("distribution/start_distribution.html")


@distribution.route("/stop")
def confirm_stop_modal():
    return render_template("distribution/confirm_stop_modal.html")


@distribution.route("/<int:p_id>", methods=["GET"])
def product(p_id):

    product = Product.query.get_or_404(p_id)

    if not product.units:
        abort(404)

    if len(product.units) == 1:
        return redirect(
            url_for(
                "distribution.distribute",
                p_id=product.id,
                p_unit_shortname=product.units[0].shortname,
            ),
            302,
        )

    return render_template("distribution/choose_unit.html", product=product)


@distribution.route("/<int:p_id>/<p_unit_shortname>")
def distribute(p_id: int, p_unit_shortname: str):

    product = Product.query.get_or_404(p_id)
    unit = Unit.query.filter_by(shortname=p_unit_shortname).first()

    if not product or not unit:
        abort(404)

    dist = Distribution.current()

    # query if existing -> ask how to proceed
    already_distributed = False
    if (
        db.session.query(Share)
        .filter(
            Share.distribution_id == dist.id,
            Share.product_id == product.id,
            Share.unit_id == unit.id,
        )
        .first()
    ):
        already_distributed = True

    stations = (
        StationHistory.query.filter(StationHistory.distribution_id == dist.id)
        .order_by(StationHistory.delivery_order)
        .all()
    )

    return render_template(
        "distribution/distribute.html",
        product=product,
        unit=unit,
        stations=stations,
        already_distributed=already_distributed,
    )


@distribution.route("/add_distribution_info", methods=["GET", "POST"])
def add_distribution_info():

    dist = Distribution.current()

    if request.method == "POST":

        if request.form.get("clear"):

            return render_template(
                "distribution/add_distribution_info_button.hx.html",
                dist_info=dist.information,
            )

        dist.information = request.form.get("info")
        db.session.commit()

        return render_template(
            "distribution/add_distribution_info_button.hx.html",
            dist_info=dist.information,
        )

    return render_template(
        "distribution/add_distribution_info.hx.html", dist_info=dist.information
    )


@distribution.route(
    "/add_product_info/<product_id>/<int:unit_id>", methods=["GET", "POST"]
)
def add_product_info(product_id, unit_id):

    product = Product.query.get_or_404(product_id)
    unit = Unit.query.get_or_404(unit_id)
    dist = Distribution.current()
    shares = Share.query.filter(
        Share.distribution_id == dist.id,
        Share.product_id == product.id,
        Share.unit_id == unit.id,
    )
    info = shares[0].information

    if request.method == "POST":

        if request.form.get("clear"):

            return render_template(
                "distribution/add_product_info_button.hx.html",
                product_id=product.id,
                unit_id=unit.id,
                product_info=info,
            )

        info = request.form.get("product-info")
        shares.update(dict(information=info))
        db.session.commit()

        return render_template(
            "distribution/add_product_info_button.hx.html",
            product_id=product.id,
            unit_id=unit.id,
            product_info=info,
        )

    return render_template(
        "distribution/add_product_info.hx.html",
        product=product,
        unit=unit,
        product_info=info,
    )


@distribution.route("/save", methods=["POST"])
def save():

    if request.content_type == "application/json":

        request_data: list = request.json
        dist = Distribution.current()
        product_id = request_data[0].get("product_id")
        unit_id = request_data[0].get("unit_id")

        poll_shares = Share.query.filter(
            Share.product_id == product_id,
            Share.distribution_id == dist.id,
            Share.unit_id == unit_id,
        )

        exclude_from_deletion = []

        for json_data in request_data:

            additional_distribution = json_data.pop("additional_distribution", None)

            data = dict(distribution_id=dist.id)
            data.update(json_data)

            _stationhistory_id = data.get("stationhistory_id")
            exclude_from_deletion.append(_stationhistory_id)
            result = poll_shares.filter(Share.stationhistory_id == _stationhistory_id)

            update_data = ShareModel(**data)

            if result.one_or_none():

                if additional_distribution:

                    entry = result.one()
                    entry.sum_full += update_data.sum_full
                    entry.sum_half += update_data.sum_half
                    entry.single_full += update_data.single_full
                    entry.single_half += update_data.single_half

                else:

                    result.update(update_data.dict())

            else:
                share = Share(**data)
                db.session.add(share)

        if not additional_distribution:
            poll_shares.filter(
                Share.stationhistory_id.notin_(exclude_from_deletion)
            ).delete()

        db.session.commit()

        return ("", 200)

    return abort(404)


@distribution.route(
    "/delete/<int:product_id>/<unit_shortname>", methods=["GET", "POST"]
)
def delete_from_distribution(product_id, unit_shortname):

    product = Product.query.get_or_404(product_id)
    unit = Unit.query.filter(Unit.shortname == unit_shortname).one_or_none()
    dist = Distribution.current()

    if request.method == "POST":

        delete_product = request.form.get("delete")
        form_product = int(request.form.get("product_id", 0))
        form_unit = int(request.form.get("unit_id", 0))

        if delete_product and (form_product == product.id) and (form_unit == unit.id):

            product_shares = Share.query.filter(
                Share.product_id == product.id,
                Share.unit_id == unit.id,
                Share.distribution_id == dist.id,
            )
            product_shares.delete()
            db.session.commit()

            flash(f"{product.name} gelöscht", category="info")
            return redirect(url_for("distribution.overview"))

        return abort(404)

    return render_template(
        "distribution/confirm_delete_modal.html", product=product, unit=unit
    )


@distribution.route("/finalize", methods=["GET", "POST"])
def finalize():

    dist: Distribution = Distribution.current()

    if request.method == "POST":

        finalize = request.form.get("finalization", False)

        if finalize and (int(finalize) == dist.id):

            product_ids = set(
                [
                    result[0]
                    for result in db.session.query(Share.product_id)
                    .filter(Share.distribution_id == dist.id)
                    .all()
                ]
            )
            products = (
                db.session.query(Product).filter(Product.id.in_(product_ids)).all()
            )

            if not products:
                flash("Leere Verteilung kann nicht gespeichert werden.", "danger")
                return redirect(url_for("distribution.overview"))

            dist.in_progress = False
            dist.finalized = True
            db.session.flush()
            dist.date_time = dist.updated

            for product in products:
                product.last_distribution = dist.updated

            db.session.commit()

            flash("Verteilung abgeschlossen!", category="info")
            return redirect(url_for("history.overview"), 302)

        return abort(404)

    return render_template(
        "distribution/confirm_finalization_modal.html", dist_id=dist.id
    )

ms/history/views.py
from typing import Dict, List
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel

from flask import Blueprint, current_app, make_response, render_template, url_for, request
from flask_weasyprint import HTML, render_pdf

from ms.db import query
from ms.db.models import (
    Distribution,
    Organisation,
    Product,
    Share,
    StationHistory,
    Unit,
    db,
)

history = Blueprint("history", __name__)


@history.route("/")
def overview():

    distributions = Distribution.query.filter(
        Distribution.in_progress == False, Distribution.finalized == True
    ).all()

    return render_template("history/history.html", distributions=distributions)


@history.route("/detail/<int:distribution_id>/<int:product_id>/<int:unit_id>")
def product_detail_view(distribution_id, product_id, unit_id):

    product = Product.query.get(product_id)
    distribution = Distribution.query.get(distribution_id)
    data = query.product_details(distribution_id, product_id, unit_id)

    return render_template(
        "history/product_detail_modal.html",
        data=data,
        product=product,
        distribution=distribution,
    )


@history.route("/stationdetails/<int:station_id>")
@history.route("/stationdetails/<int:station_id>/<pdf_station_name>.pdf")
def station_distribution_details(station_id, pdf_station_name=None):

    station = StationHistory.query.get_or_404(station_id)
    shares = Share.query.filter(Share.stationhistory_id == station.id).all()
    csa = Organisation.query.first()

    if pdf_station_name:

        if not station.pdf:

            # make pdf
            css = [Path("ms/static/customisation.css"), Path("ms/static/style.css")]
            html = render_template(
                "history/station_details.pdf.html",
                station=station,
                shares=shares,
                csa=csa,
                pdf=True,
            )
            pdf = HTML(string=html)

            # write to db
            distribution_time = station.distribution.date_time
            pdf_path = Path(
                current_app.instance_path,
                "files/pdf",
                distribution_time.strftime(f"%Y%m%d-%H%M-{station.name}.pdf"),
            )
            pdf.write_pdf(target=pdf_path, stylesheets=css)
            station.pdf = pdf_path.as_posix()

            db.session.commit()

        pdf_path = Path(station.pdf)
        filename = pdf_path.name
        pdf_response = make_response(pdf_path.read_bytes())
        pdf_response.headers["Content-Type"] = "application/pdf"
        pdf_response.headers["Content-Disposition"] = f"inline; filename={filename}"

        return pdf_response

    return render_template(
        "history/station_details_modal.html", station=station, shares=shares, csa=csa
    )


@history.route("/tools/show-recent-distributions/<int:product_id>/<int:unit_id>")
def show_recent_distribution(product_id, unit_id):

    product = Product.query.get_or_404(product_id)
    unit = Unit.query.get_or_404(unit_id)
    how_many_distributions = 6

    result = query.show_recent_distribution(
        product, unit, how_many_distributions=how_many_distributions
    )

    return render_template(
        "history/tools/show_recent_distribution_modal.html",
        data=result,
        product=product,
        unit=unit,
        how_many_distributions=how_many_distributions,
    )


@history.route("/chart/stations")
def station_chart():

    stations = {}
    for station_id in db.session.query(StationHistory.station_id).distinct().all():

        result = (
            db.session.query(
                StationHistory.name,
                StationHistory.time_archived,
                StationHistory.members_total,
            )
            .filter(StationHistory.station_id == station_id[0])
            .all()
        )
        name = result[-1][0]
        stations[name] = result

    return render_template("history/station_chart.html", stations=stations)


@history.route("/chart/products")
def product_chart():
    return render_template("history/product_chart.html")


@history.route("/api/products")
def api_products():
    products = Product.query.all()
    return [{"id": product.id, "name": product.name} for product in products]


class ProductData(BaseModel):
    distribution_date: str
    value: float

class UnitProductData(BaseModel):
    total: float
    unit_name: str
    data: List[ProductData]

class ProductResponse(BaseModel):
    id: int
    name: str
    data: Dict[str, UnitProductData]

@history.route("/api/product")
def api_product() -> ProductResponse:

    request_args = request.args
    product_id = request_args.get("product_id")
    product = Product.query.get_or_404(product_id)

    start_time = datetime.strptime( request_args.get("start_date"), "%Y-%m-%d")
    end_time = datetime.strptime( request_args.get("end_date"), "%Y-%m-%d")

    def time_filter(share) -> bool:
        if start_time <= share.dist.date_time and share.dist.date_time <= end_time:
            return True
        return False
    filtered_data = [share for share in filter(time_filter, product.shares)]

    # extremely inefficient as this would be lot faster in DB. will do it in
    # python as the query rewrite is off the limits for now. fetch all dist ids
    dist_ids = list(set([share.dist.id for share in filtered_data]))
    dist_ids.sort()


    data = {}
    for dist_id in dist_ids:
        # fetch all shares for this distribution
        shares = [share for share in filtered_data if share.dist.id == dist_id]

        share_unit_name = shares[0].unit.longname

        shares_total = sum([share.sum_total for share in shares])

        if share_unit_name not in data.keys():
            data[share_unit_name] = {
                "total": shares_total,
                "data": [
                ProductData(
                    distribution_date=shares[0].dist.date_time.strftime("%Y-%m-%d"),
                    value=shares_total,
                    )],
                "unit_name": share_unit_name,
            }
        else:
            data[share_unit_name]["total"] += shares_total
            data[share_unit_name]["data"].append(
                ProductData(
                    distribution_date=shares[0].dist.date_time.strftime("%Y-%m-%d"),
                    value=shares_total,
                )
            )

    return ProductResponse(
        id=product.id,
        name=product.name,
        data=data,
    ).dict()

ms/templates/distribution/add_distribution_info.hx.html
<div class="is-pulled-right">
<form id="add-distribution-info-form"
      method="POST"
      action="{{url_for('distribution.add_distribution_info')}}">
  <div class="field has-addons">
    <div class="control">
      <input  id="add-distribution-info-input"
              type="text"
              placeholder="Info für diese Verteilung"
              class="input"
              size="77"
              {%- if dist_info -%}
              value="{{dist_info}}"
              {%- endif -%}
              name="info"/>
    </div>
    <div class="control">
      <button class="button is-info"
              id="add-distribution-info-submit-button"
              type="submit"
              hx-post="{{url_for('distribution.add_distribution_info')}}"
              hx-target="#add-distribution-info"
              hx-swap="innerHTML"
              >info speichern</button>
    </div>
    <div class="control">
      <a class="button is-info is-light"
              id="add-distribution-info-abort-button"
              type="submit"
              hx-params="clear"
              hx-post="{{url_for('distribution.add_distribution_info')}}"
              hx-target="#add-distribution-info"
              hx-swap="innerHTML"
              >x</a>
    </div>
  </div>
</form>
</div>

ms/templates/distribution/add_distribution_info_button.hx.html
<div class="columns mt-2">
  <div class="column is-9">
    {% if dist_info %}{{ dist_info }}{% endif %}
    </div>
  <div class="column is-3">
<button class="button is-link is-light"
        id="add-distribution-info-button"
        hx-get="{{url_for("distribution.add_distribution_info")}}"
        hx-target="#add-distribution-info"
        hx-swap="innerHTML"
        >Info für Lieferschein bearbeiten</button>
    </div>
</div>

ms/templates/distribution/add_product_info.hx.html
<div class="is-pulled-right">
  <form id="add-info-form"
        method="POST"
        action="{{ url_for('distribution.add_product_info', product_id=product.id, unit_id=unit.id) }}">

    <div class="field has-addons">
      <div class="control">
        <input  name="product-info"
                type="text"
                size=55
                placeholder="Info für {{ product.name }}"
                class="input"
                {%- if product_info -%}
                value="{{product_info}}"
                {%- endif -%}
                id="input-add-info"/>
      </div>
      <div class="control">
        <button class="button is-info"
                id="save-info"
                type="submit"
                hx-post="{{url_for('distribution.add_product_info', product_id=product.id, unit_id=unit.id) }}"
                hx-target="#info-div-{{product.id}}-{{unit.id}}"
                hx-swap="innerHTML"
                >info speichern</button>
      </div>
      <div class="control">
        <a class="button is-info is-light"
                id="save-info"
                type="submit"
                hx-params="clear"
                hx-post="{{url_for('distribution.add_product_info', product_id=product.id, unit_id=unit.id) }}"
                hx-target="#info-div-{{product.id}}-{{unit.id}}"
                hx-swap="innerHTML"
                >x</a>
      </div>
    </div>
  </form>
</div>

ms/templates/distribution/add_product_info_button.hx.html
{# some parsing as overview has a weird query working right now
    and this template is working in multiple places #}


{% if product %}
  {% if product.product_id %}
    {% set product_id = product.product_id %}
  {% endif %}
  {% if product.unit_id %}
    {% set unit_id = product.unit_id %}
  {% endif %}
  {% if product.info %}
    {% set product_info = product.info %}
  {% endif %}
{% endif %}

<div class="columns">
  <div class="column has-text-left is-italic">
    {% if product_info %}{{ product_info }}{% endif %}
  </div>

  <div class="column is-4 has-text-right">
      <button class="button is-small is-link is-light"
              hx-get="{{url_for('distribution.add_product_info', product_id=product_id, unit_id=unit_id ) }}"
              hx-target="#info-div-{{product_id}}-{{unit_id}}"
              hx-swap="innerHTML"
              id="add-info">Info bearbeiten</button>
  </div>
</div>

ms/templates/distribution/confirm_delete_modal.html
{% extends 'modal.html' %}
{% block modal_content %}
<div class="columns is-centered is-multiline">
  <div class="column is-full has-text-centered">
    <p><small>sicher {{ product.name }} aus dieser verteilung löschen?</small></p>
  </div>
  <div class="column is-half has-text-centered">
    <form method="POST"
          action="{{url_for('distribution.delete_from_distribution', product_id=product.id, unit_shortname=unit.shortname) }}"
          id="confirm-deletion-form"
          >
      <input type="hidden"
             name="delete"
             value="1"
             />
      <input type="hidden"
             name="unit_id"
             value="{{unit.id}}"
             />
      <input type="hidden"
             name="product_id"
             value="{{product.id}}"
             />
      <button id="confirm-deletion-button"
              class="button is-warning"
              type="submit"
              >{{product.name}} löschen</button>
    </form>
  </div>
</div>

{% endblock modal_content %}

ms/templates/distribution/confirm_finalization_modal.html
{% extends 'modal.html' %}
{% block modal_content %}
<div class="columns is-centered is-multiline">
  <div class="column is-full has-text-centered">
    <p>Diese Verteilung so abschließen?</p>
    <div class="column is-three-quarters has-text-left content">
      <p><small>Danach nicht mehr änderbar. Abgeschlossene Verteilungen werden</small></p>
      <ul>
        <li>archiviert</li>
        <li>lieferscheine werden generiert</li>
        <li>statistiken erstellt</li>
      </ul>
    </div>
    <p>Sind Sie sicher dass alles verteilt wurde?</p>
  </div>

  <form id="confirm-finalization-form"
        action="{{ url_for('distribution.finalize') }}"
        method="POST"
        >
    <input type="hidden"
           name="finalization"
      value="{{ dist_id }}"/>
    <button id="confirm-finalization-button"
            class="button is-primary"
            type="submit">
    Verteilung fertigstellen</button>
  </form>
</div>
{% endblock modal_content %}

ms/templates/distribution/distribute.html
{% extends 'base.html' %}
{% from 'macros.html' import number_input %}
{% from 'macros.html' import modal with context %}
{% set title = product.name + ' verteilen' %}

{% block scripts %}
{% include 'distribution/dist.js.html' %}
{% endblock %}

{% block content %}

<div class="columns is-multiline" id="dist-stations-area">

  {# Info #}
  <div class="column is-full">
    <div class="level">
      {% if product.last_distribution %}
      <div class="level-left">
        <div class="level-item has-text-weight-medium">Zuletzt:</div>
        <div class="level-item">{{ moment(product.last_distribution).fromNow() }},</div>
        <div class="level-item">{{ moment(product.last_distribution).format("LLL") }}</div>
      </div>
      {% endif %}
      {% if product.info %}
      <div class="level-right">
        <div class="level-item">
          <img class="mr-2" src="{{url_for('static', filename='icons/info.svg')}}" width=18 />
          {{ product.info }}
        </div>
      </div>
      {% endif %}
    </div>
  </div>

  {# error and message for dist.js script #}
  <div class="column expand" id="dist-error-div">
    <div class="columns is-centered">
      <div class="column is-half bordered has-text-centered has-background-danger has-text-black" id="dist-error-field"></div>
    </div>
  </div>
  <div class="column expand" id="dist-message-div">
    <div class="columns is-centered">
      <div class="column is-half bordered has-text-centered has-background-light has-text-black" id="dist-message-field"></div>
    </div>
  </div>

  {# Verteilung Input and Rest #}
  <div class="column is-full">

    <div class="columns is-mobile is-centered is-multiline">

      {# Input area #}
      <div class="column is-one-third-desktop is-full-mobile">

        <div class="columns is-mobile is-centered">
          <div class="column is-half is-half-mobile has-text-centered">
            <input type="number"
                   class="input"
                   value="{{ product.amount }}"
                   id="dist-input-field"
                   />
            <label for="dist-input-field"
                  class="label">Ernte <small>( in {{ unit.longname }} )</small></label>
          </div>
        </div>

        {# tools #}
        <div class="column">
          tools:
          <div class="row">
            <a class="button is-small is-light"
               id="recent-distributions"
               {{ modal(url_for("history.show_recent_distribution", product_id=product.id, unit_id=unit.id)) }}
               >Letzte Wochen</a>
          </div>
        </div>

      </div>

      {# buttons #}
      <div class="column is-one-third-desktop is-full-mobile">

        {# add or overwrite buttons #}
        {% if already_distributed %}
        <div class="row">
          <div class="column is-full has-text-centered">
            <p class="has-text-weight-medium">{{ product.name }} wurde schon verteilt!</p>
            <p>Zusätzlich verteilen oder komplett überschreiben?</p>
          </div>
          <div class="field is-grouped is-grouped-centered mb-2">
            <div class="control">
              <label class="radio button">
                <input type="radio"
                       name="additional_distribution"
                       id="overwrite-distribution-input"
                       value="false"
                       >
                  überschreiben
              </label>
              <label class="radio button">
                <input type="radio"
                       name="additional_distribution"
                       id="additional-distribution-input"
                       value="true"
                       checked
                       >
                  zusätzlich
              </label>
            </div>
          </div>
        </div>
        {% endif %}

        {# distribute buttons #}
        <div class="row">
          <div class="field is-grouped is-grouped-centered">
            <div class="control">
              <button class="button is-link dist-button-toggle"
                      id="dist-button-even"
                      onclick="distribute('even')"
                      >gleich</button>
            </div>
            <div class="control">
              <button class="button is-link dist-button-toggle"
                      id="dist-button-half"
                      onclick="distribute('half')"
                      >halbe halb</button>
            </div>
            <div class="control">
              <button class="button is-link dist-button-toggle"
                      id="dist-button-none"
                      onclick="distribute('none')"
                      >halbe nix</button>
            </div>
          </div>
        </div>

      </div>

      {# rest and extra buttons #}
      <div class="column is-one-third-desktop is-half-mobile">

        <div class="row">
          <div class="columns is-centered">
            <div class="column is-4 has-text-centered bordered">
              {% if unit.by_piece %}
              <div class="row is-size-4">Rest</div>
              <div class="row"><p class="is-size-3" id="dist-rest-field">𐄂</p></div>
              {% else %}
              <div class="row is-size-4">Rest</div>
              <div class="row"><p class="is-size-3" id="dist-accuracy-field">𐄂</p></div>
              {% endif %}
            </div>
          </div>
          <div class="row">
            <div class="columns is-centered">
              <div class="column is-full has-text-centered">
                <button class="button is-large is-success bordered-dash"
                        id="save-button"
                        onclick="save_data()"
                        disabled>Speichern</button>
              </div>
            </div>
          </div>
        </div>


      </div>

    </div>

  </div>

  {# station boxes #}
  {% for station in stations %}
    {% include 'distribution/station_box.html' %}
  {% endfor %}

</div>

{% endblock %}

ms/templates/distribution/overview.html
{% from 'macros.html' import modal with context %}
{% extends 'base.html' %}
{% set title = 'Verteilung' %}
{% block content %}


<div class="columns is-centered is-multiline">

  <div class="column is-full has-text-centered">
    <p>gestartet:</p><p id="info-dist-started"><small>{{ moment(dist.created).format("LLL") }}</small></p>
  </div>

  <div class="column is-11">
    <table class="table is-fullwidth">
      <col style="width:15%">
      <col style="width:10%">
      <col style="width:55%">
      <col style="width:10%">
      <col style="width:10%">
      <thead class="has-text-centered">
        <td>Name</td>
        <td>Verteilt</td>
        <td>Info an die Mitglieder</td>
      </thead>

    {% for product in data %}
      <tr class="product-row has-text-centered" id="overview-{{product.product_id}}-{{product.unit_name}}">
        <td class="has-text-left ml-5">{{product.name}} <small>in {{product.unit_name}}</small></td>
        <td>{{product.total_sum|round(2,"floor")}}</td>
        <td class="has-text-right"><div id="info-div-{{product.product_id}}-{{product.unit_id}}">{% include "distribution/add_product_info_button.hx.html" %}</div></td>
        <td class="has-text-centered">
          <button class="button is-light is-link is-small"
            id="detail_view"
            {{ modal(url_for('history.product_detail_view', distribution_id=dist.id, product_id=product.product_id, unit_id=product.unit_id )) }}
            >detail</button>
        </td>
        <td class="has-text-centered">
          <button class="button is-light is-link is-small"
                  id="delete-from-distribution-{{product.product_id}}-{{product.unit_name}}"
                  {{ modal(url_for('distribution.delete_from_distribution', product_id = product.product_id, unit_shortname = product.unit_shortname)) }}
                  >löschen</button>
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>
</div>


<div class="columns is-centered is-multiline">
  <div class="column is-10">
    <div id="add-distribution-info" class="has-text-right">
      {% include "distribution/add_distribution_info_button.hx.html" %}
    </div>
  </div>
  <div class="column is-10">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <a {{ modal(url_for('distribution.confirm_stop_modal') ) }}
              href="{{ url_for('distribution.confirm_stop_modal') }}">
            <button class="button is-link is-light"
                  id="stop-distribution-modal"
                  >Verteilung stoppen</button>
          </a>
        </div>
      </div>

      <div class="level-right">

        <div class="level-item">
          <a {{ modal(url_for('distribution.finalize') ) }}
              href="{{ url_for('distribution.finalize') }}">
            <button class="button is-link is-light"
                  id="finalize-distribution-modal"
                  >Verteilung fertigstellen</button>
          </a>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock content%}