ms/stations/views.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from sqlalchemy import func

from ms.db.forms import StationForm
from ms.db.models import Distribution, Station, db

stations = Blueprint("stations", __name__)


@stations.route("/")
def stations_view():

    stations = Station.query.order_by(Station.delivery_order).all()

    query = db.session.query(
        func.sum(Station.members_full).label("full"),
        func.sum(Station.members_half).label("half"),
    ).one()
    station_totals = {
        "total_full": query.full if query.full else 0,
        "total_half": query.half if query.half else 0,
    }

    return render_template(
        "stations/stations.html", stations=stations, totals=station_totals
    )


@stations.route("/edit/<int:stationid>", methods=["POST"])
def edit(stationid):

    if Distribution.current().in_progress:
        return abort(404)

    station = Station.query.get(stationid)
    form = StationForm(request.form, obj=station)

    form.populate_obj(station)

    if form.validate():
        db.session.add(station)
        db.session.commit()

        return redirect(url_for("stations.stations_view"), 302)

    flash("something went wrong...", category="warning")
    return redirect(url_for("stations.stations_view"), 302)


@stations.route("/stationsdetail/<int:stationid>")
def detail_view(stationid):

    if Distribution.current().in_progress:
        return abort(404)

    station = Station.query.get(stationid)
    form = StationForm(request.form, station)

    return render_template("stations/detail_view.html", station=station, form=form)


@stations.route("/new", methods=["GET", "POST"])
def new_station():

    if Distribution.current().in_progress:
        return abort(404)

    station = Station()
    form = StationForm(request.form)
    form.populate_obj(station)

    if request.method == "POST" and form.validate():

        db.session.add(station)
        db.session.commit()

        return redirect(url_for("stations.stations_view"), 302)

    return render_template("stations/new.html", form=form)


@stations.route("/delete/<int:station_id>", methods=["POST"])
def delete(station_id):

    station = Station.query.get_or_404(station_id)

    if station.deleted_at:
        abort(404)

    station.delete()
    db.session.commit()

    return redirect(url_for("stations.stations_view"))

ms/templates/stations/detail_view.html
{% extends 'modal.html' %}
{% block modal_content %}
  <h3 class="title is-3">{{station.name}}</h3>
  {% if station.updated %}
    <div class="level">
      <div class="level-left">
        <div class="is-size-7 is-italic level-item">zuletzt bearbeitet:</div>
        <div class="is-size-7 is-italic level-item date-time">{{station.updated}}</div>
      </div>
    </div>
  {% endif %}
  <a href="#" id="delete-station-form-expand has-text-centered"
              class="button is-small is-warning is-light"
              onclick="document.querySelector('#delete-station').classList.toggle('expand')
              ">station löschen</a>
  {% set form_action = url_for('stations.delete', station_id=station.id) %}
  <form id="delete-station"
        class="row has-text-centered expand mt-2"
        action = "{{ form_action }}"
        method="POST"
        >
    <button class="button is-warning">station endgültig löschen</button>
  </form>
  <hr class="edit-hr">
  {% set form_action = url_for('stations.edit', stationid=station.id) %}
  {% set form_params = 'id=station-edit-form' %}
  {% include 'stations/form.html' %}
{% endblock modal_content %}

ms/templates/stations/form.html
<div class="columns mt-2 is-centered">
<div class="column is-8 has-text-centered">

  <form action={{form_action }}
        method="post"
        {{ form_params }}
        class="form">

  {{ form.csrf_token }}

  <div class="field">
    {{ form.name.label("Name der Station", class_="label") }}
    {{ form.name(placeholder="Stationsname XYZ", class_="input") }}
  </div>
  <div class="field">
      <label for="delivery_order">
        <div class="label mb-0">Liefer- und Sortierreihenfolge</div>
        <div class="is-size-7 is-italic mb-1">
          Niedrigere Zahlen werden zuerst beliefert, wird auch so in den Übersichten sortiert
        </div>

      </label>
    {{ form.delivery_order(placeholder=0, class_="input") }}
  </div>
  <div class="field">
    {{ form.info.label("Informationen zur Station", class_="label") }}
    {{ form.info(placeholder="Anschrift, Kontaktmöglichkeiten, ...", class_="input") }}
  </div>
  <div class="field has-addons">
    <div class="control">
    {{ form.members_full.label("Ganze Anteile", class_="label") }}
    {{ form.members_full(placeholder=0, class_="input is-medium") }}
    </div>
    <div class="control">
    {{ form.members_half.label("Halbe Anteile", class_="label") }}
    {{ form.members_half(placeholder=0, class_="input is-medium") }}
    </div>
  </div>

  <button class="button is-link" type="submit">Go!</button>
  </form>
</div>
</div>

ms/templates/stations/new.html
{% extends 'modal.html' %}
{% block modal_content %}
<h4 class="title is-4">Neue Station anlegen</h4>

{% set form_action = url_for('stations.new_station') %}
{% include 'stations/form.html' %}

{% endblock %}

ms/templates/stations/stations.html
{% extends 'base.html' %}

{% set title = 'Stationen' %}

{% block content %}
<div class="rows">
  <div class="row">

    <div class="level">
      <div class="level-left">
        <div id="totals" class="level-item has-text-centered">
          <div class="p-1" id="totals-full">
            Ganze Anteile: {{ totals.total_full }}
          </div>
          <div class="p-1" id="totals-half">
            Halbe Anteile: {{ totals.total_half }}
          </div>
          <div class="p-1" id="totals-sum">
            Anteile: {{ totals.total_full + (totals.total_half/2) }}
          </div>
        </div>
      </div>

      <div class="level-right">
        <div class="level-item">
          {% if distribution_in_progress %}
            <p class="p-3 is-italic" id="text-station-in-distribution">Aktuell in Verteilung - Stationen nicht editierbar</p>
          {% else %}
             <button class="button is-link"
                     hx-get="{{ url_for('stations.new_station') }}"
                     hx-target="body"
                     hx-swap="beforeend">neue station</button>
          {% endif %}
        </div>
      </div>
    </div>


    <div class="columns is-multiline">
    {% for station in stations %}
      <div class="column is-4" id="{{station.order}}">
        <div class="box" id="box-station-{{station.id}}">
          <div class="columns is-multiline">
            <div class="column">
              <h2 class="level-left is-size-2 has-text-weight-medium is-primary has-text-dark">
                {{ station.name }}
              </h2>
            </div>
          <div class="column is-2">
            {% if not distribution_in_progress %}
              <a id="station-edit-view-{{station.id}}"
                    hx-get="{{ url_for('stations.detail_view', stationid=station.id) }}"
                    hx-target="body"
                    hx-swap="beforeend">
                <img src="{{url_for('static', filename='icons/edit.svg')}}" width=24 />
              </a>
            {% endif %}
          </div>
          </div>
        <p>
        <img class="" src="{{url_for('static', filename='icons/users.svg') }}" width=18 />
        {{ station.members_total }}
        ● {{ station.members_full }}
        ◑ {{station.members_half }}
        </p>
        {% if station.info %}
          <div class="has-text-weight-light mt-2">
            <img src="{{url_for('static', filename='icons/info.svg') }}" width=18 />
            {{ station.info }}
          </div>
        {% endif %}
        </div> {# end div box #}
      </div>
    {% endfor %}
    </div>

  </div>

</div>
{% endblock %}