ms/history/views.py
from typing import Dict, List
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel

from flask import Blueprint, current_app, make_response, render_template, url_for, request
from flask_weasyprint import HTML, render_pdf

from ms.db import query
from ms.db.models import (
    Distribution,
    Organisation,
    Product,
    Share,
    StationHistory,
    Unit,
    db,
)

history = Blueprint("history", __name__)


@history.route("/")
def overview():

    distributions = Distribution.query.filter(
        Distribution.in_progress == False, Distribution.finalized == True
    ).all()

    return render_template("history/history.html", distributions=distributions)


@history.route("/detail/<int:distribution_id>/<int:product_id>/<int:unit_id>")
def product_detail_view(distribution_id, product_id, unit_id):

    product = Product.query.get(product_id)
    distribution = Distribution.query.get(distribution_id)
    data = query.product_details(distribution_id, product_id, unit_id)

    return render_template(
        "history/product_detail_modal.html",
        data=data,
        product=product,
        distribution=distribution,
    )


@history.route("/stationdetails/<int:station_id>")
@history.route("/stationdetails/<int:station_id>/<pdf_station_name>.pdf")
def station_distribution_details(station_id, pdf_station_name=None):

    station = StationHistory.query.get_or_404(station_id)
    shares = Share.query.filter(Share.stationhistory_id == station.id).all()
    csa = Organisation.query.first()

    if pdf_station_name:

        if not station.pdf:

            # make pdf
            css = [Path("ms/static/customisation.css"), Path("ms/static/style.css")]
            html = render_template(
                "history/station_details.pdf.html",
                station=station,
                shares=shares,
                csa=csa,
                pdf=True,
            )
            pdf = HTML(string=html)

            # write to db
            distribution_time = station.distribution.date_time
            pdf_path = Path(
                current_app.instance_path,
                "files/pdf",
                distribution_time.strftime(f"%Y%m%d-%H%M-{station.name}.pdf"),
            )
            pdf.write_pdf(target=pdf_path, stylesheets=css)
            station.pdf = pdf_path.as_posix()

            db.session.commit()

        pdf_path = Path(station.pdf)
        filename = pdf_path.name
        pdf_response = make_response(pdf_path.read_bytes())
        pdf_response.headers["Content-Type"] = "application/pdf"
        pdf_response.headers["Content-Disposition"] = f"inline; filename={filename}"

        return pdf_response

    return render_template(
        "history/station_details_modal.html", station=station, shares=shares, csa=csa
    )


@history.route("/tools/show-recent-distributions/<int:product_id>/<int:unit_id>")
def show_recent_distribution(product_id, unit_id):

    product = Product.query.get_or_404(product_id)
    unit = Unit.query.get_or_404(unit_id)
    how_many_distributions = 6

    result = query.show_recent_distribution(
        product, unit, how_many_distributions=how_many_distributions
    )

    return render_template(
        "history/tools/show_recent_distribution_modal.html",
        data=result,
        product=product,
        unit=unit,
        how_many_distributions=how_many_distributions,
    )


@history.route("/chart/stations")
def station_chart():

    stations = {}
    for station_id in db.session.query(StationHistory.station_id).distinct().all():

        result = (
            db.session.query(
                StationHistory.name,
                StationHistory.time_archived,
                StationHistory.members_total,
            )
            .filter(StationHistory.station_id == station_id[0])
            .all()
        )
        name = result[-1][0]
        stations[name] = result

    return render_template("history/station_chart.html", stations=stations)


@history.route("/chart/products")
def product_chart():
    return render_template("history/product_chart.html")


@history.route("/api/products")
def api_products():
    products = Product.query.all()
    return [{"id": product.id, "name": product.name} for product in products]


class ProductData(BaseModel):
    distribution_date: str
    value: float

class UnitProductData(BaseModel):
    total: float
    unit_name: str
    data: List[ProductData]

class ProductResponse(BaseModel):
    id: int
    name: str
    data: Dict[str, UnitProductData]

@history.route("/api/product")
def api_product() -> ProductResponse:

    request_args = request.args
    product_id = request_args.get("product_id")
    product = Product.query.get_or_404(product_id)

    start_time = datetime.strptime( request_args.get("start_date"), "%Y-%m-%d")
    end_time = datetime.strptime( request_args.get("end_date"), "%Y-%m-%d")

    def time_filter(share) -> bool:
        if start_time <= share.dist.date_time and share.dist.date_time <= end_time:
            return True
        return False
    filtered_data = [share for share in filter(time_filter, product.shares)]

    # extremely inefficient as this would be lot faster in DB. will do it in
    # python as the query rewrite is off the limits for now. fetch all dist ids
    dist_ids = list(set([share.dist.id for share in filtered_data]))
    dist_ids.sort()


    data = {}
    for dist_id in dist_ids:
        # fetch all shares for this distribution
        shares = [share for share in filtered_data if share.dist.id == dist_id]

        share_unit_name = shares[0].unit.longname

        shares_total = sum([share.sum_total for share in shares])

        if share_unit_name not in data.keys():
            data[share_unit_name] = {
                "total": shares_total,
                "data": [
                ProductData(
                    distribution_date=shares[0].dist.date_time.strftime("%Y-%m-%d"),
                    value=shares_total,
                    )],
                "unit_name": share_unit_name,
            }
        else:
            data[share_unit_name]["total"] += shares_total
            data[share_unit_name]["data"].append(
                ProductData(
                    distribution_date=shares[0].dist.date_time.strftime("%Y-%m-%d"),
                    value=shares_total,
                )
            )

    return ProductResponse(
        id=product.id,
        name=product.name,
        data=data,
    ).dict()

ms/templates/history/history.html
{% from 'macros.html' import modal with context %}

{% extends 'base.html' %}

{% set title = 'History' %}

{% block styles %}
<link rel="stylesheet" type="text/css"
      href="{{ url_for('static', filename='assets/jquery.dataTables.css') }}">
{% endblock styles %}

{% block scripts %}
<script type="text/javascript" charset="utf8"
        src="{{ url_for('static', filename='assets/jquery-3.6.0.min.js') }}"></script>
<script type="text/javascript" charset="utf8"
        src="{{ url_for('static', filename='assets/jquery.dataTables.js') }}"></script>
<script>
 $(document).ready(function() {
    $('#history-overview-table').DataTable({
        paging: false,
        responsive: true,
        order: [[0, 'desc'], [1, 'desc']],
        columnDefs: [
          {
            targets:1,
            render: DataTable.render.datetime("DD. MMMM HH:mm", "de"),
          },
          ],
        columns: [
        null,
        null,
        {orderable: false, searchable: true},
        ]
    });
  });
</script>
{% endblock scripts %}

{% block content %}
  <div class="column is-10 is-centered has-text-centered">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <a class="button is-link" href="{{url_for('history.station_chart')}}">Stationen Statistik</a>
        </div>
        <div class="level-item">
          <a class="button is-link" href="{{url_for('history.product_chart')}}">Produkte Statistik</a>
        </div>
      </div>
    </div>
  </div>

  <table class="table is-hoverable is-fullwidth is-narrow"
           id="history-overview-table">
    <col style="width:10%">
    <col style="width:20%">
    <col style="width:70%">
    <thead>
      <tr>
        <th>Jahr</th>
        <th>Verteilung</th>
        <th>Stationen</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Jahr</th>
        <th>Verteilung</th>
        <th>Stationen</th>
      </tr>
    </tfoot>
    <tbody>
    {% for dist in distributions %}
      <tr id="distribution-{{dist.id}}">
        {% set year = dist.date_time.strftime("%Y") -%}
        <td>{{ year }}</td>
        <td>{{dist.date_time}}</td>
        <td>
          <div class="is-capitalized">
        {% for station in dist.stations %}
            <a {{modal(url_for('history.station_distribution_details', station_id=station.id))}}
               class="p-1 m-3 has-text-link-dark">{{ station.name }}</a>
        {% endfor %}
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

ms/templates/history/product_chart.html
{% extends 'base.html' %}

{% block scripts %}
<script src="{{ url_for('static', filename='assets/chart.min.js') }}"></script>
<script>
  {% include 'history/charts/products.js' %}
</script>
{% endblock scripts %}

{% block content %}

<div class="columns is-multiline is-centered">
  <div class="column is-11 has-text-centered">
    <h1 class="title">Produkte Statistik</h1>
    <div id="products-buttons" class="columns is-multiline is-5">
      <button class="button is-secondary is-small is-hidden" id="all-products-button"></button>
    </div>
      <h1 id="product-name"
           class="has-text-centered has-text-weight-bold"></h2>
      <div id="product-details"></div>
      <small>Wähle ein Produkt aus der Liste</small>
      <label for="start-date-picker">Start Zeitraum:</label>
      <input type="date" id="start-date-picker" name="start-date" value="2000-01-01" min="2000-01-01" max="2111-01-01" />
      <label for="end-date-picker">Bis:</label>
      <input type="date" id="end-date-picker" name="end-date" value="2999-01-01" min="2000-00-00" max="2222-01-01" />
      <button class="button is-secondary is-small" onclick="updateChart()" id="update-chart-button">Aktualisieren</button>
      <div id="product-chart-area"></div>
  </div>
</div>

{% endblock content %}

ms/templates/history/product_detail_modal.html
{% extends 'modal.html' %}
{% block modal_content %}
  <div class="columns is-centered is-multiline">
    <div class="is-size-3 column is-full has-text-centered">
      {{ product.name }}
    </div>
    <div class="column is-full has-text-centered">
      <div class="date-time">{{ distribution.date_time }}</div>
      in {{ data[0].unit_name }}
    </div>

    {% for detail in data %}
      <div class="column is-one-third">
        <div class="rows">
          <div class="row">
            <div class="is-size-4 has-text-weight-medium">
              {{ detail.Share.stationhistory.name }}
            </div>
          </div>
        </div>

        <div class="columns is-multiline mt-2">
          <div class="column p-1 is-6 has-text-weight-medium">Gesamt</div>
          <div class="column p-1 is-5 has-text-weight-medium">{{ detail.Share.sum_total|round(2,"floor" )}}</div>
          <div class="column p-1 is-6">Ganze</div>
          <div class="column p-1 is-5">{{ detail.Share.single_full|round(2,"floor" ) }}</div>
          <div class="column p-1 is-6">Halbe</div>
          <div class="column p-1 is-5">{{ detail.Share.single_half|round(2,"floor" ) }}</div>
        </div>
    </div>
    {% endfor %}
  </div>

{% endblock modal_content %}

ms/templates/history/station_chart.html
{% extends 'base.html' %}

{% block scripts %}
<script src="{{ url_for('static', filename='assets/chart.min.js') }}"></script>
<script>
  {% include 'history/charts/stations.js' %}
</script>
{% endblock scripts %}

{% block content %}

<div class="columns is-multiline is-centered">
  <div class="column is-11 has-text-centered">
    Mitgliederanzahl der Stationen im Verlauf
    <p class="is-size-7 is-italic">Mitglieder, nicht anteile</p>
    <canvas id="station-chart"></canvas>
  </div>
</div>

{% endblock content %}

ms/templates/history/station_details.pdf.html
{# for printing PDF #}
<style>html{background-color:#FFFFFF}</style>

<div class="rows has-text-black">
  <div class="row">
    <div class="columns">
      <div class="column is-3 is-pulled-left">
        <div class="has-text-weight-semi-bold is-size-3">{{ station.name }}</div>
        {% if pdf %}
          <div class="row has-text-weight-light">{{ station.distribution.date_time.strftime("%-d.%m.%Y, %H:%M") }}</div>
        {% else %}
          <div class="row has-text-weight-light date-time">{{ station.distribution.date_time }}</div>
        {% endif %}
      </div>
      <div class="column is-3 is-pulled-right">
      {% if pdf %}
        <div class="is-size-4">
         LOGO
        </div>
        <div>{{ csa.name }}</div>
      {% endif %}
      </div>
    </div>
  </div>

  <div class="row has-background-white">
    <table class="table is-fullwidth has-background-white">
      <thead>
        <td>Erzeugniss</td>
        <td>Einheit</td>
        <td>Ganzer Anteil</td>
        <td>Halber Anteil</td>
      </thead>
      <tbody class="has-background-white">
      {% for share in shares %}
        {% if share.unit.by_piece %}
          {% set full = share.single_full|int %}
          {% set half = share.single_half|int %}
        {% else %}
          {% set full = share.single_full|round(precision=3, method='floor') %}
          {% set half = share.single_half|round(precision=3, method='floor') %}
        {% endif %}

        {% if full == 0 and half == 0 %}{% continue %}{% endif %}
        <tr>
          <td>{{ share.product.name }}</td>
          <td>{{ share.unit.longname }}</td>
          <td>{% if full %}{{ full }}{% else %}/{% endif %}</td>
          <td>{% if half %}{{ half }}{% else %}/{% endif %}</td>
        </tr>
        {% if share.information %}
        <tr>
          <td colspan=4><p class="ml-5 is-size-6 is-italic">↪ {{ share.information }}</p></td>
        </tr>
        {% endif %}
      {% endfor %}
      </tbody>
    </table>
  </div>

  <hr>

  {% if station.distribution.information %}
  <div class="row">
    <p class="has-text-centered">Info</p>
    <p class="is-size-6 has-text-centered is-italic">{{ station.distribution.information }}</p>
  </div>
  {% endif %}

  <div class="row mt-5">
        {{ station.members_total }} Mitglieder in dieser Station, davon {{ station.members_full }} Ganze und {{ station.members_half }} Halbe.
  </div>

  {% if pdf %}
  <div class="row mt-5 has-text-right is-italic">
    {{ csa.footer }}
  </div>
  {% endif %}

</div>

ms/templates/history/station_details_modal.html
{% extends 'modal.html' %}
{% block modal_content %}
<div class="has-text-centered">
  <a  id="pdf-link"
      class="button"
      href="{{url_for('history.station_distribution_details', station_id=station.id, pdf_station_name=station.name) }}"
      target="blank"
      >PDF</a>
</div>
{% include 'history/station_details.pdf.html' %}
{% endblock modal_content %}